test

diff --git a/.github/workflows/new_infra.yml b/.github/workflows/new_infra.yml
--- a/.github/workflows/new_infra.yml
+++ b/.github/workflows/new_infra.yml
@@ -172,15 +172,43 @@ jobs:
           terraform plan -input=false -out=tfplan -var-file=../clients/${{ inputs.client_name }}/${{ inputs.client_code }}.tfvars
         continue-on-error: true
 
-      - name: Update issue
+      - name: terraform apply
+        id: tfapply
+        working-directory: terraform
+        run: |
+          set -o pipefail
+          terraform apply -auto-approve -input=false -var-file=../clients/${{ inputs.client_name }}/${{ inputs.client_code }}.tfvars
+        continue-on-error: true
+
+      # One summary comment (always), includes the link
+      - name: Report Terraform status to issue
         uses: AgentSprint/utils-actions/issues/comment-on@main
         with:
           issue_api_url: ${{ inputs.issue_api_url }}
           body: |
-            ✅ terraform plan successfull
+            📝 Terraform summary for **${{ inputs.client_code }}** @ **${{ inputs.location }}**:
+            - Plan:  ${{ steps.tfplan.outcome == 'success' && '✅ Success' || '❌ Failed' }}
+            - Apply: ${{ steps.tfapply.outcome == 'success' && '✅ Success' || '❌ Failed' }}
+
+            ${{ (steps.tfplan.outcome != 'success' || steps.tfapply.outcome != 'success') && format('🔗 Run details: ', env.RUN_URL) || '' }}
           token: ${{ secrets.GH_TOKEN }}
 
+      - name: cleanup deleting branch as it failed
+        if: steps.tfplan.outcome != 'success' || steps.tfapply.outcome != 'success'
+        uses: AgentSprint/utils-actions/repo/branch/delete@main
+        with:
+            owner: "AgentSprint"
+            repo: "infra-azure"
+            branch_name: "adding_new_client_${{ inputs.client_code }}"
+            token: ${{ secrets.GH_TOKEN }}
+
+      # Finally, fail the job if either step failed
+      - name: Fail job if Terraform failed
+        if: steps.tfplan.outcome != 'success' || steps.tfapply.outcome != 'success'
+        run: exit 1
+
       - name: Merge a pull request
+        if: steps.tfplan.outcome == 'success' || steps.tfapply.outcome == 'success'
         uses: AgentSprint/utils-actions/pull_request/merge@main
         with:
             owner: "AgentSprint"
@@ -189,6 +217,7 @@ jobs:
             token: ${{ secrets.GH_TOKEN }}
 
       - name: Update issue
+        if: steps.tfplan.outcome == 'success' || steps.tfapply.outcome == 'success'
         uses: AgentSprint/utils-actions/issues/comment-on@main
         with:
           issue_api_url: ${{ inputs.issue_api_url }}
@@ -204,39 +233,6 @@ jobs:
             branch_name: "adding_new_client_${{ inputs.client_code }}"
             token: ${{ secrets.GH_TOKEN }}
 
-      - name: terraform apply
-        id: tfapply
-        working-directory: terraform
-        run: |
-          set -o pipefail
-          terraform apply -auto-approve -input=false -var-file=../clients/${{ inputs.client_name }}/${{ inputs.client_code }}.tfvars
-        continue-on-error: true
-
-      - name: Update issue
-        uses: AgentSprint/utils-actions/issues/comment-on@main
-        with:
-          issue_api_url: ${{ inputs.issue_api_url }}
-          body: |
-            ✅ terraform apply successfully completed
-          token: ${{ secrets.GH_TOKEN }}
-
-      # One summary comment (always), includes the link
-      - name: Report Terraform status to issue
-        uses: AgentSprint/utils-actions/issues/comment-on@main
-        with:
-          issue_api_url: ${{ inputs.issue_api_url }}
-          body: |
-            📝 Terraform summary for **${{ inputs.client_code }}** @ **${{ inputs.location }}**:
-            - Plan:  ${{ steps.tfplan.outcome == 'success' && '✅ Success' || '❌ Failed' }}
-            - Apply: ${{ steps.tfapply.outcome == 'success' && '✅ Success' || '❌ Failed' }}
-
-            ${{ (steps.tfplan.outcome != 'success' || steps.tfapply.outcome != 'success') && format('🔗 Run details: ', env.RUN_URL) || '' }}
-          token: ${{ secrets.GH_TOKEN }}
-
-      # Finally, fail the job if either step failed
-      - name: Fail job if Terraform failed
-        if: steps.tfplan.outcome != 'success' || steps.tfapply.outcome != 'success'
-        run: exit 1
 
       - name: close request issues
         uses: AgentSprint/utils-actions/issues/close@main
